before:
  hooks:
    - task test
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/genwith
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
announce:
  skip: "true"

brews:
  - name: genwith
    homepage: https://github.com/bzimmer/genwith
    description: Code generation tool for client with functional options
    license: MIT
    commit_author:
      name: bzimmer
      email: bzimmer@ziclix.com
    tap:
      owner: bzimmer
      name: homebrew-tap
    skip_upload: auto
    install: bin.install "genwith"
